#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

# cookbook 'chef-client'

# cookbook 'apache2', '>= 1.0.0'

cookbook 'build-essential'
cookbook 'apt'
cookbook 'rvm', :git => 'git://github.com/fnichol/chef-rvm.git'
cookbook 'git'
cookbook 'user'
cookbook 'nginx'
cookbook 'python'
cookbook 'nodejs'
cookbook 'mono'
cookbook 'php'
cookbook 'mysql', '~> 5.3.6'
cookbook 'apache2'
cookbook 'composer', '~> 1.0.4'